services:
  backend:
    build: .
    environment:
      SPRING_CLOUD_AWS_CREDENTIALS_ACCESS-KEY: ${AWS_ACCESS_KEY}
      SPRING_CLOUD_AWS_CREDENTIALS_SECRET-KEY: ${AWS_SECRET_KEY}
      SPRING_CLOUD_AWS_REGION_STATIC: ${AWS_REGION}
      SPRING_CLOUD_AWS_SQS_ENDPOINT: ${SQS_ENDPOINT}
    ports:
      - "8080:8080"

